MvcBookStore/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBookStore.ViewModel;
using MvcBookStore.Models;

namespace MvcBookStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        //
        // GET: /ShoppingCart/
        IShoppingCart _shoppingCart;
        IBookRepository _bookRepository;
        public ShoppingCartController()
        {
            _shoppingCart = new ShoppingCart();
            _bookRepository = new BookRepository();
        }

        public ActionResult Index()
        {
            _shoppingCart.GetCartId(this.HttpContext);
            //初始化视图模型
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = _shoppingCart.GetCartItems(),
                CartTotal = _shoppingCart.GetTotal()
            };
            return View(viewModel);
        }
        public ActionResult AddToCart(int id)
        {
            _shoppingCart.GetCartId(this.HttpContext);
            //确定id是否有效
            Books b = _bookRepository.GetBookById(id);
            if (b != null)
            {
                _shoppingCart.AddToCart(id);
            }
            //回到购物车首页
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            _shoppingCart.GetCartId(this.HttpContext);
            //获取书籍信息返回确认消息
            Books b = _shoppingCart.GetBookByRecordId(id);
            //从购物车删除
            int itemCount = _shoppingCart.RemoveFromCart(id);
            //确认显示消息
            var results=new ShoppingCartRemoveViewModel
            {
                Message=Server.HtmlEncode("《"+b.Title+"》")+"已经从购物车中删除",
                CartTotal=_shoppingCart.GetTotal(),
                CartCount=_shoppingCart.GetCount(),
                ItemCount=itemCount,
                DeleteId=id

            };
            return Json(results);
        }
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            _shoppingCart.GetCartId(this.HttpContext);
            ViewData["CartCount"]=_shoppingCart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

MvcBookStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBookStore.Models;
namespace MvcBookStore.Controllers
{
    public class StoreController : Controller
    {
        //GET:/Store/CategoryMenu
        [ChildActionOnly]
        public ActionResult CategoryMenu()
        {
            return PartialView(_categoryRepository.GetAllCategories());
        }

        ICategoryRepository _categoryRepository;
        public StoreController()
        {
            _categoryRepository = new CategoryRepository();
        }

        //
        // GET: /Store/
        public ActionResult Index()
        {
            return View(_categoryRepository.GetAllCategories());
        }
        //
        // GET: /Store/Browse
        public ActionResult Browse(int id)
        {
            //根据类别id获取书籍
            return View(_categoryRepository.GetCategoriesById(id));
        }
        //
        // GET: /Store/Details
        public ActionResult Details(int id)
        {
            //根据书籍id获取获取详细书籍信息
            return View(_categoryRepository.GetBooksById(id));
        }



    }
}

MvcBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - 我的 ASP.NET MVC 应用程序</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div id="setWidth">
            @if (Request.IsAuthenticated)
            {
                <text >
                你好，@Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: null, htmlAttributes: new { @class = "username", title = "管理" })!
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                    <a href="javascript:document.getElementById('logoutForm').submit()">注销</a>
                }
                </text>
            }
            else
            {

                <ul>
                    <li>@Html.ActionLink("注册", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                    <li>@Html.ActionLink("登录", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                </ul>
            }
            <div id="header">
              
                <h1><a href="/">网上书店</a></h1>
              
                <ul id="navlist">
                    <li class="first"><a href="@Url.Content("~")" id="current">首页</a></li>
                    @*<li><a href="@Url.Content("~/ShoppingCart/")">购物车</a></li>*@
                   <li>@{Html.RenderAction("CartSummary", "ShoppingCart");}</li>
                    <li><a href="@Url.Content("~/StoreManager/")">管理页</a></li>
                </ul>
            </div>
            @RenderSection("featured", required: false)
            @{Html.RenderAction("CategoryMenu", "Store");}
            <div id="main" style="width:800px;height:auto">
                @RenderBody()
            </div>
            <div id="footer">
                <p>&copy;@DateTime.Now.Year-我的MVC应用程序</p>
            </div>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>